int32 event_limit
---
bool success
string message
string mission_state
string previous_mission_state
string active_mission_id
string mission_message
bool recoverable
bool mission_active
bool paused
int32 queue_size
string[] queued_mission_ids
int32[] queued_priorities
string[] paused_workflow_order_ids
string[] fleet_robot_ids
bool[] fleet_enabled
string[] fleet_states
float64[] fleet_battery_voltage
string[] fleet_current_station_ids
string[] fleet_capabilities
string[] remote_task_ids
string[] remote_task_robot_ids
string[] remote_task_states
string[] facility_resource_ids
string[] facility_resource_types
string[] facility_station_ids
bool[] facility_available
string[] facility_status
string[] business_types
string[] business_scenario_ids
string[] business_workflow_ids
string[] recent_event_stamp
string[] recent_event_mission_ids
string[] recent_event_states
string[] recent_event_messages
