<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>amr_dispatcher_tools</name>
  <version>1.0.0</version>
  <description>CLI interface (replxx) and REST gateway tools for amr_dispatcher</description>
  <maintainer email="tanqf@example.com">tanqf</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>amr_dispatcher_core</depend>
  <depend>amr_dispatcher_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
